### ISSUE TITLE
How can I use this source code for Ubuntu 22.04

### ISSUE THREAD

**Issue by dinhthihuyen** [horejsek/python-webapp-example#1]
In Ubuntu 22.04, package dh-systemd is no longer available. How can I use your code in Ubuntu 22.04?
Thanks so much for your support!!!

**Comment by horejsek** [comment]
Hi. Note this is from 2018. :-) I didn't use it for few years. It seems that dh-systemd is now part of debhelper (https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=822670), so simple dependency update could help.

**Comment by dinhthihuyen** [comment]
Dear @horejsek, 
I have another question and I need your help!!!
After packaging using make build and install using make install, how can I start webapp using debian file.
In my code, instead of building a web app, I run a program with main function. I added main function in entrypoint in setup.py.
And now, after building its as debian package, how can I start it - my program?
Thanks so much for your support!!

**Comment by horejsek** [comment]
It depends on the type of the app. Either you have some web server or other service that is always running, and then you need to define service. Example for web server running with uwsgi is here: https://github.com/horejsek/python-webapp-example/blob/master/debian/webapp.webapp.service

Or you can have cmd tool, that you need to just install in proper place using links, for example, and then call as any other tool installed on your system: https://github.com/horejsek/python-webapp-example/blob/master/debian/webapp.links

Please refer to documentation of debian packaging. There are tons of options and conventions to follow that this example cannot cover. My example is just very brief quick example of a specific setup (Python server using Flask framework with uwsgi and nginx packed in Debian app) to start with.
